os: osx
osx_image: xcode11.6
language: objective-c
#xcode_project: AcrolinxPluginSamples/AcrolinxPluginTextEdit/AcrolinxPluginTextEdit.xcodeproj
#xcode_scheme: AcrolinxPluginTextEdit
before_script: cd AcrolinxPluginSamples
script: xcodebuild build 