git:
  depth: 45
addons:
  sonarcloud:
    organization: acrolinx
    token:
      secure: qONkvTXhImKC2BshJde3xgGyMWYg29nz81JSZd6+LTrugMT7NKYXRk2PjJ51m8JOF3uq+tWOo/LTToRvRxaTDS9N2WMoMLl7d8NBNv2t+E4YdDaF34o/CpUEnEPvGcP69xTg9TttC7zVrfo8RyY+NIsg4kgcMbFXCS07QI72Zet75uBWlQR2h0XmT7MEyASssdW8s6vWeHMPkJu3JaqhMiV5gcjXXWna78dGUr4Gao9WJcsBi5UP7zw1IDcpb/yR/lMG1lrCqMVUxIKBtVeiwZjf8VDOeAg/n7/kIhFIAuhkCllnLLpf4MDJtucww1rVuFSX6m9WUOJg7bAillTK6YtcJWMRIyIk1Y7yFXUC8ILwZWh70fJV9LngnpWC0bDcr7kMA/xeiP9okgJVM2Mv1UyqFcdue0xZ3H/9cBBqRL2eM2Ti364dMhOLVXKxFASz8JI8xfvFvrUZ7EaaGiO6SXKnLoWgwXPsV3f4Ew1g1PPAH/yWb978WqxfjMYfg6We2+338on07kR8YZ8hfILsXh0nX+92jXEU2GtH6LlMDVWF1Pa/0AIEKgxLXevroQ37tlS01xlh7sGFO3jbn3t4oq0Z09UPGEezH0ucIQMPPr1uChmBFdkUq+/KrV/ioCPutRVUvsVfSmpI2t2I0HOiKBTMbOfUZdoajBFqIGGiib4=
os: osx
osx_image: xcode11.6
language: objective-c
script:
- git fetch --unshallow
- cd AcrolinxPluginSamples/AcrolinxPluginTextEdit
- build-wrapper-macosx-x86 --out-dir ../../bw-output xcodebuild build
- cd ..
- cd ..
- brew install tree
- tree
- sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
