addons:
  sonarcloud:
    organization: acrolinx
    token:
      secure: IKFOaQnbHfSVzjCD+auvS4Sd/xlFzhI9YUWFCg372smxRYe+BhYd6f0rjcGY9LLtDJBflQY9QUFWYm5O4te0Z6LjxLGeVTYrNL9QVNNkIZNQ5XIf31SbAMPp8i3wlg6+G9Vs6zJOlyrivhjlBR7+LH4MNBCc+E8kWZQLs3kC0pJDTQlvI/h7yWjwoyXzXycioUBT5nBH2lMJc3TLfQZyB75lTmFqoGsHCXAQuW3GBmsKclBVO0EMnG1VGsjOZ/5Kf7sDKccc6rAlVUtj/RBpy0fDXTzg4onkr8aLpVac1SqZHxJcO1cPlwE9xJpXcttD2HR0F+01USVdZYsvOcvJlsPX0Wp/zkxv+ohm0BEsexFneV0y9uau/RWrUwGiMk4g3sYnv73SLerLj3ytBGFrLTsVKOz6qkOQB8oo+BHO8TriNs7lPdYzOBWo2QYFpE1RqWyPJ/UDhJLBZwFWl6gwOO8OQQ7xnXK4z++0h5oRO2PhEN00Wz98aWMcO1lMiWRbj4Jm9hqoSIphIWGsNktKerqNRX33Xq0DH4VETXn9M1JgLoeLnZhKIemTTKfRN4fXT2G+hC4PhkUdcSTd7hZxkDwkPqFfc1PG3MAtcEezNFvEaXG2uWQXteAi9Y316XTSKAqZPUnRKnvyKNOCf76sweO6rS5wgyus0znG9v1VPoI=
os: osx
osx_image: xcode11.6
language: objective-c
before_script: cd AcrolinxPluginSamples/AcrolinxPluginTextEdit
script:
- xcodebuild build
- sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
